# This file is part of xrootdpyfs
# Copyright (C) 2015-2020 CERN.
#
# xrootdpyfs is free software; you can redistribute it and/or modify it under
# the terms of the Revised BSD License; see LICENSE file for more details.

python:
 - "2.7"

python:
  - "2.7"
  - "3.6"

services:
  - docker

env:
  - REQUIREMENTS=devel
  - REQUIREMENTS=latest
  - REQUIREMENTS=lowest

cache:
  - docker

install:
  - "docker build -t xrootd ."
  - "docker run -h xrootdpyfs -t -u root xrootd pip install -r requirements.${REQUIREMENTS}.txt"
  - "travis_retry pip install --user coveralls pydocstyle Sphinx twine wheel"

script:
  - "docker run -h xrootdpyfs -t xrootd"

after_success:
  - coveralls

notifications:
  email: false
